[auth]
allowed_redirect_urls = [
  "http://localhost:3002/api/auth/callback",
  "http://127.0.0.1:3002/api/auth/callback",
  "https://f3efi8df.insforge.site/api/auth/callback",
]

[deployments]
subdomain = "matchday"
